mod.id = "texting_colonists"
mod.name = "Texting Colonists (Talking Colonists Add-On)"
mod.group = "me.sshcrack.texting_colonists"
mod.version = "1.0.0"
mod.channel_tag = ""
mod.description = "Enables you to text the citizens in talking colonists"
mod.authors = ["sshcrack"]
mod.contributors = []
mod.inception_year = "2025"
mod.license.name = "All rights reserved"
mod.license.url = "(no url)"
mod.license.dist = "repo"
mod.sources_url = "https://github.com/sshcrack/texting-colonists-addon"
mod.homepage_url = "https://github.com/sshcrack/texting-colonists-addon"
mod.issues_url = "https://github.com/sshcrack/texting-colonists-addon/issues"
mod.discord_url = ""

[[mod.pom.developers]]
id = "me.sshcrack"
name = "sshcrak"
url = "https://github.com/sshcrack/"

[forge]

[forge."1.20.1"]
deps.minecraft = "1.20.1"
deps.forge = "47.2.0"


[neoforge]

[neoforge."1.21.1"]
deps.minecraft = "1.21.1"
deps.parchment = "1.21.1:2024.11.17"
deps.neoforge = "21.1.213"
